site_name: Furious Frogs
site_url: https://furiousfrogs.github.io/team26025/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
nav:
  - Home: index.md
  - Team members: members.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
