site_name: Furious Frogs
site_url: https://<your-username>.github.io/ftc-team-site/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
nav:
  - Home: index.md
  - Team members: team.md
  - News:
      - Scrimmage: news/scrimmage.md
  - Robots:
      - 2023-2024: robots/2023-2024.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
